server:
  port: 8989
  context-path: /gh
  jsp-servlet:
    init-parameters:
      development: true


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.ln.entity
  mapper-locations: classpath:/mapper/*Mapper.xml